# --- Stage 1: Build ---
FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server/main.go

# --- Stage 2: Runtime ---
FROM alpine:3.19

WORKDIR /app

# бинарник
COPY --from=builder /app/server .

# миграции
COPY --from=builder /app/internal/db/migrations ./internal/db/migrations

EXPOSE 9000

CMD ["./server"]
